#!/usr/bin/env node
// Golden vectors for the front chain CLI's Program Metadata encoders
// (front/scripts/chain/lib/program-metadata.ts), generated by calling
// @solana-program/program-metadata itself (the version installed here).
//
// Usage (from program/): node scripts/fixtures/pm-vectors.mjs > ../front/tests/fixtures/program-metadata-0.8.0.json
//
// Offline: builds instructions and PDAs only. No RPC, no keypair file, no
// randomness, no timestamp — the output is byte-stable for a given PM version,
// so the front test can compare it whole.
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as pm from '@solana-program/program-metadata';
import { createNoopSigner, getAddressDecoder } from '@solana/kit';

const require = createRequire(import.meta.url);
// The package's `exports` hides package.json; walk up from its entry point.
let pmRoot = path.dirname(require.resolve('@solana-program/program-metadata'));
while (!existsSync(path.join(pmRoot, 'package.json'))) pmRoot = path.dirname(pmRoot);
const pmPackage = readFileSync(path.join(pmRoot, 'package.json'));
const here = path.dirname(fileURLToPath(import.meta.url));

const key = (n) => getAddressDecoder().decode(new Uint8Array(32).fill(n));
const REGISTRY = 'FJs1EM1ND89L9sUXaS8VBKYXjmoXCkkVSJKRE19hmYxS';
const HOOK = 'GBDyesyTr266LqKeFq95r1DeigRyHpfw6ACWdjENHAPy';
const AUTHORITY = key(7);
const BUFFER = key(9);
const METADATA = key(11);
const PROGRAM_DATA = key(13);
const DESTINATION = key(15);
const NEW_AUTHORITY = key(17);
const signer = createNoopSigner(AUTHORITY);
const bufferSigner = createNoopSigner(BUFFER);
const data = Uint8Array.from({ length: 37 }, (_, i) => (i * 7 + 3) & 0xff);
const header = {
  encoding: pm.Encoding.Utf8,
  compression: pm.Compression.Zlib,
  format: pm.Format.Json,
  dataSource: pm.DataSource.Direct,
};

const view = (ix) => ({
  program: ix.programAddress,
  accounts: ix.accounts.map((a) => [a.address, a.role]),
  dataB64: Buffer.from(ix.data).toString('base64'),
});

const instructions = {
  write: pm.getWriteInstruction({ buffer: BUFFER, authority: signer, offset: 1800, data }),
  writeFromSource: pm.getWriteInstruction({ buffer: BUFFER, authority: signer, offset: 0, sourceBuffer: METADATA }),
  initializeCanonicalNoData: pm.getInitializeInstruction({
    metadata: METADATA, authority: signer, program: REGISTRY, programData: PROGRAM_DATA,
    system: pm.PROGRAM_METADATA_PROGRAM_ADDRESS, seed: 'idl', ...header, data: undefined,
  }),
  initializeWithData: pm.getInitializeInstruction({
    metadata: METADATA, authority: signer, program: REGISTRY, programData: PROGRAM_DATA, seed: 'idl', ...header, data,
  }),
  setAuthorityBuffer: pm.getSetAuthorityInstruction({ account: BUFFER, authority: bufferSigner, newAuthority: AUTHORITY }),
  setAuthorityCanonical: pm.getSetAuthorityInstruction({
    account: METADATA, authority: signer, program: REGISTRY, programData: PROGRAM_DATA, newAuthority: NEW_AUTHORITY,
  }),
  setAuthorityNone: pm.getSetAuthorityInstruction({
    account: METADATA, authority: signer, program: REGISTRY, programData: PROGRAM_DATA, newAuthority: null,
  }),
  setDataFromBuffer: pm.getSetDataInstruction({
    metadata: METADATA, authority: signer, buffer: BUFFER, program: REGISTRY, programData: PROGRAM_DATA, ...header, data: undefined,
  }),
  setDataInline: pm.getSetDataInstruction({
    metadata: METADATA, authority: signer, program: REGISTRY, programData: PROGRAM_DATA, ...header, data,
  }),
  setImmutable: pm.getSetImmutableInstruction({ metadata: METADATA, authority: signer, program: REGISTRY, programData: PROGRAM_DATA }),
  trim: pm.getTrimInstruction({ account: METADATA, authority: signer, program: REGISTRY, programData: PROGRAM_DATA, destination: DESTINATION }),
  closeBuffer: pm.getCloseInstruction({ account: BUFFER, authority: signer, destination: DESTINATION }),
  allocateCanonical: pm.getAllocateInstruction({ buffer: METADATA, authority: signer, program: REGISTRY, programData: PROGRAM_DATA, seed: 'idl' }),
  allocateBuffer: pm.getAllocateInstruction({ buffer: BUFFER, authority: bufferSigner }),
  extendCanonical: pm.getExtendInstruction({ account: METADATA, authority: signer, program: REGISTRY, programData: PROGRAM_DATA, length: 10240 }),
};

const pdas = {};
for (const [name, program] of [['asset_registry', REGISTRY], ['transfer_hook', HOOK]]) {
  const [canonical] = await pm.findCanonicalPda({ program, seed: 'idl' });
  pdas[name] = canonical;
}

const metadataAccount = pm.getMetadataEncoder().encode({
  program: REGISTRY, authority: null, mutable: true, canonical: true, seed: 'idl', ...header, dataLength: data.length, data,
});
const metadataWithAuthority = pm.getMetadataEncoder().encode({
  program: HOOK, authority: NEW_AUTHORITY, mutable: false, canonical: true, seed: 'idl', ...header, dataLength: data.length, data,
});
const bufferAccount = pm.getBufferEncoder().encode({
  program: null, authority: AUTHORITY, canonical: false, seed: '', data,
});

const output = {
  schema: 'mancipatio-pm-golden-vectors-v1',
  generator: path.relative(path.resolve(here, '../../..'), fileURLToPath(import.meta.url)),
  pmVersion: JSON.parse(pmPackage).version,
  pmPackageJsonSha256: createHash('sha256').update(pmPackage).digest('hex'),
  constants: {
    programAddress: pm.PROGRAM_METADATA_PROGRAM_ADDRESS,
    accountHeaderLength: pm.ACCOUNT_HEADER_LENGTH,
    reallocLimit: 10240,
  },
  keys: { AUTHORITY, BUFFER, METADATA, PROGRAM_DATA, DESTINATION, NEW_AUTHORITY, REGISTRY, HOOK },
  dataB64: Buffer.from(data).toString('base64'),
  canonicalIdlPdas: pdas,
  instructions: Object.fromEntries(Object.entries(instructions).map(([name, ix]) => [name, view(ix)])),
  accounts: {
    metadata: Buffer.from(metadataAccount).toString('base64'),
    metadataWithAuthority: Buffer.from(metadataWithAuthority).toString('base64'),
    buffer: Buffer.from(bufferAccount).toString('base64'),
  },
};
process.stdout.write(`${JSON.stringify(output, null, 2)}\n`);
