/**
 * Program Metadata (PM) 0.8.0 encoders and decoders on kit 5 codecs.
 *
 * `@solana-program/program-metadata` 0.8.0 needs kit ^7 and cannot be
 * imported into front (kit 5.5.1), so the instructions are re-encoded here.
 * The account order and the optional-account placeholder (the PM program id,
 * read-only) mirror `src/generated/instructions/*` of that package; golden
 * vectors generated by PM itself (program/scripts/fixtures/pm-vectors.mjs →
 * front/tests/fixtures/program-metadata-0.8.0.json) pin the bytes.
 */
import { deflateSync, inflateSync } from "node:zlib";
import {
  AccountRole,
  address,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getProgramDerivedAddress,
  getUtf8Encoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Instruction,
  type TransactionSigner,
} from "@solana/kit";
import { SYSTEM_PROGRAM } from "./loader-v3";

export const PM_PROGRAM = address("ProgM6JCCvbYkfKqJYHePx4xxSUSqJp7rh8Lyv7nk7S");
export const SYSVAR_RENT = address("SysvarRent111111111111111111111111111111111");
export const PM_HEADER_LENGTH = 96;
export const PM_REALLOC_LIMIT = 10_240;
/** Write chunk size used by the CLI (a write transaction stays well under 1232 B). */
export const PM_WRITE_CHUNK = 900;
export const IDL_SEED = "idl";

export const PmDiscriminator = {
  Write: 0,
  Initialize: 1,
  SetAuthority: 2,
  SetData: 3,
  SetImmutable: 4,
  Trim: 5,
  Close: 6,
  Allocate: 7,
  Extend: 8,
} as const;

export const AccountKind = { Empty: 0, Buffer: 1, Metadata: 2 } as const;
export const Encoding = { None: 0, Utf8: 1, Base58: 2, Base64: 3 } as const;
export const Compression = { None: 0, Gzip: 1, Zlib: 2 } as const;
export const Format = { None: 0, Json: 1, Yaml: 2, Toml: 3 } as const;
export const DataSource = { Direct: 0, Url: 1, External: 2 } as const;

/** The IDL header the CLI writes and expects: Utf8 + Zlib + Json + Direct. */
export const IDL_HEADER = {
  encoding: Encoding.Utf8,
  compression: Compression.Zlib,
  format: Format.Json,
  dataSource: DataSource.Direct,
} as const;

const addressEncoder = getAddressEncoder();
const addressDecoder = getAddressDecoder();
const seedEncoder = fixEncoderSize(getUtf8Encoder(), 16);

export function encodeSeed(seed: string): Uint8Array {
  if (Buffer.byteLength(seed, "utf8") > 16) throw new Error("PM seeds are at most 16 bytes");
  return new Uint8Array(seedEncoder.encode(seed));
}

/** Canonical metadata PDA: [program, seed(16)] under the PM program. */
export async function findCanonicalMetadataPda(program: Address, seed = IDL_SEED): Promise<Address> {
  const [pda] = await getProgramDerivedAddress({
    programAddress: PM_PROGRAM,
    seeds: [addressEncoder.encode(program), encodeSeed(seed)],
  });
  return pda;
}

// ── Account metas ────────────────────────────────────────────────────────────

type Account = Address | TransactionSigner;

function isSigner(value: Account): value is TransactionSigner {
  return typeof value === "object" && value !== null && "address" in value;
}

/** Codama `getAccountMetaFactory(programId, 'programId')`. */
function accountMeta(value: Account | null | undefined, writable: boolean): AccountMeta | AccountSignerMeta {
  if (!value) return { address: PM_PROGRAM, role: AccountRole.READONLY };
  if (isSigner(value)) {
    return {
      address: value.address,
      role: writable ? AccountRole.WRITABLE_SIGNER : AccountRole.READONLY_SIGNER,
      signer: value,
    };
  }
  return { address: value, role: writable ? AccountRole.WRITABLE : AccountRole.READONLY };
}

function instruction(accounts: (AccountMeta | AccountSignerMeta)[], data: Uint8Array): Instruction {
  return { programAddress: PM_PROGRAM, accounts, data };
}

function bytes(...parts: (number | Uint8Array)[]): Uint8Array {
  const chunks = parts.map((part) => (typeof part === "number" ? Uint8Array.of(part) : part));
  const out = new Uint8Array(chunks.reduce((sum, chunk) => sum + chunk.length, 0));
  let offset = 0;
  for (const chunk of chunks) {
    out.set(chunk, offset);
    offset += chunk.length;
  }
  return out;
}

function u32le(value: number): Uint8Array {
  const out = new Uint8Array(4);
  new DataView(out.buffer).setUint32(0, value, true);
  return out;
}

function u16le(value: number): Uint8Array {
  const out = new Uint8Array(2);
  new DataView(out.buffer).setUint16(0, value, true);
  return out;
}

type CanonicalAccounts = { program?: Address | null; programData?: Address | null };
type Header = { encoding: number; compression: number; format: number; dataSource: number };

// ── Instructions ─────────────────────────────────────────────────────────────

/** write (0): [buffer w, authority s, sourceBuffer?]; data = u8, u32 offset, bytes?. */
export function pmWrite(input: {
  buffer: Address;
  authority: TransactionSigner;
  offset: number;
  data?: Uint8Array | null;
  sourceBuffer?: Address | null;
}): Instruction {
  return instruction(
    [accountMeta(input.buffer, true), accountMeta(input.authority, false), accountMeta(input.sourceBuffer, false)],
    bytes(PmDiscriminator.Write, u32le(input.offset), input.data ?? new Uint8Array()),
  );
}

/** initialize (1): [metadata w, authority s, program, programData?, system]. */
export function pmInitialize(
  input: CanonicalAccounts &
    Header & {
      metadata: Address;
      authority: TransactionSigner;
      program: Address;
      system?: Address | null;
      seed: string;
      data?: Uint8Array | null;
    },
): Instruction {
  return instruction(
    [
      accountMeta(input.metadata, true),
      accountMeta(input.authority, false),
      accountMeta(input.program, false),
      accountMeta(input.programData, false),
      accountMeta(input.system ?? SYSTEM_PROGRAM, false),
    ],
    bytes(
      PmDiscriminator.Initialize,
      encodeSeed(input.seed),
      input.encoding,
      input.compression,
      input.format,
      input.dataSource,
      input.data ?? new Uint8Array(),
    ),
  );
}

/** setAuthority (2): [account w, authority s, program?, programData?]; data = u8, Option<Address> (u8 prefix). */
export function pmSetAuthority(
  input: CanonicalAccounts & { account: Address; authority: TransactionSigner; newAuthority: Address | null },
): Instruction {
  return instruction(
    [
      accountMeta(input.account, true),
      accountMeta(input.authority, false),
      accountMeta(input.program, false),
      accountMeta(input.programData, false),
    ],
    input.newAuthority
      ? bytes(PmDiscriminator.SetAuthority, 1, new Uint8Array(addressEncoder.encode(input.newAuthority)))
      : bytes(PmDiscriminator.SetAuthority, 0),
  );
}

/** setData (3): [metadata w, authority s, buffer w?, program?, programData?]. */
export function pmSetData(
  input: CanonicalAccounts &
    Header & { metadata: Address; authority: TransactionSigner; buffer?: Address | null; data?: Uint8Array | null },
): Instruction {
  return instruction(
    [
      accountMeta(input.metadata, true),
      accountMeta(input.authority, false),
      accountMeta(input.buffer, true),
      accountMeta(input.program, false),
      accountMeta(input.programData, false),
    ],
    bytes(
      PmDiscriminator.SetData,
      input.encoding,
      input.compression,
      input.format,
      input.dataSource,
      input.data ?? new Uint8Array(),
    ),
  );
}

/** setImmutable (4): [metadata w, authority s, program?, programData?]. */
export function pmSetImmutable(
  input: CanonicalAccounts & { metadata: Address; authority: TransactionSigner },
): Instruction {
  return instruction(
    [
      accountMeta(input.metadata, true),
      accountMeta(input.authority, false),
      accountMeta(input.program, false),
      accountMeta(input.programData, false),
    ],
    bytes(PmDiscriminator.SetImmutable),
  );
}

/** trim (5): [account w, authority s, program?, programData?, destination w, rent]. */
export function pmTrim(
  input: CanonicalAccounts & { account: Address; authority: TransactionSigner; destination: Address },
): Instruction {
  return instruction(
    [
      accountMeta(input.account, true),
      accountMeta(input.authority, false),
      accountMeta(input.program, false),
      accountMeta(input.programData, false),
      accountMeta(input.destination, true),
      accountMeta(SYSVAR_RENT, false),
    ],
    bytes(PmDiscriminator.Trim),
  );
}

/** close (6): [account w, authority s, program?, programData?, destination w]. */
export function pmClose(
  input: CanonicalAccounts & { account: Address; authority: TransactionSigner; destination: Address },
): Instruction {
  return instruction(
    [
      accountMeta(input.account, true),
      accountMeta(input.authority, false),
      accountMeta(input.program, false),
      accountMeta(input.programData, false),
      accountMeta(input.destination, true),
    ],
    bytes(PmDiscriminator.Close),
  );
}

/** allocate (7): [buffer w, authority s, program?, programData?, system]; data = u8, Option<seed> (no prefix). */
export function pmAllocate(
  input: CanonicalAccounts & {
    buffer: Address;
    authority: TransactionSigner;
    system?: Address | null;
    seed?: string | null;
  },
): Instruction {
  return instruction(
    [
      accountMeta(input.buffer, true),
      accountMeta(input.authority, false),
      accountMeta(input.program, false),
      accountMeta(input.programData, false),
      accountMeta(input.system ?? SYSTEM_PROGRAM, false),
    ],
    input.seed ? bytes(PmDiscriminator.Allocate, encodeSeed(input.seed)) : bytes(PmDiscriminator.Allocate),
  );
}

/** extend (8): [account w, authority s, program?, programData?]; data = u8, u16 length. */
export function pmExtend(
  input: CanonicalAccounts & { account: Address; authority: TransactionSigner; length: number },
): Instruction {
  if (!Number.isInteger(input.length) || input.length <= 0 || input.length > PM_REALLOC_LIMIT) {
    throw new Error(`PM extend length must be 1..${PM_REALLOC_LIMIT}`);
  }
  return instruction(
    [
      accountMeta(input.account, true),
      accountMeta(input.authority, false),
      accountMeta(input.program, false),
      accountMeta(input.programData, false),
    ],
    bytes(PmDiscriminator.Extend, u16le(input.length)),
  );
}

/** Splits `total` extra bytes into extend lengths of at most 10,240. */
export function extendLengths(total: number): number[] {
  const out: number[] = [];
  for (let left = total; left > 0; left -= PM_REALLOC_LIMIT) out.push(Math.min(left, PM_REALLOC_LIMIT));
  return out;
}

/** [offset, chunk] pairs of at most `size` bytes. */
export function writeChunks(data: Uint8Array, size = PM_WRITE_CHUNK): [number, Uint8Array][] {
  const out: [number, Uint8Array][] = [];
  for (let offset = 0; offset < data.length; offset += size) out.push([offset, data.subarray(offset, offset + size)]);
  return out;
}

// ── Account decoders ─────────────────────────────────────────────────────────

export type MetadataAccount = {
  program: Address;
  authority: Address | null;
  mutable: boolean;
  canonical: boolean;
  seed: string;
  encoding: number;
  compression: number;
  format: number;
  dataSource: number;
  dataLength: number;
  data: Uint8Array;
  accountLength: number;
};

const ZERO_KEY = new Uint8Array(32);
function optionalZeroKey(slice: Uint8Array): Address | null {
  return Buffer.from(slice).equals(Buffer.from(ZERO_KEY)) ? null : addressDecoder.decode(slice);
}

function seedString(slice: Uint8Array): string {
  let end = slice.length;
  while (end > 0 && slice[end - 1] === 0) end--;
  return Buffer.from(slice.subarray(0, end)).toString("utf8");
}

/** Metadata layout: disc 0, program 1, authority 33 (zeroes = none), mutable 65,
 *  canonical 66, seed 67..83, encoding 83, compression 84, format 85,
 *  dataSource 86, dataLength u32 87 (+5 padding), data 96.. */
export function decodeMetadataAccount(data: Uint8Array): MetadataAccount | null {
  if (data.length < PM_HEADER_LENGTH || data[0] !== AccountKind.Metadata) return null;
  const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
  const dataLength = view.getUint32(87, true);
  if (PM_HEADER_LENGTH + dataLength > data.length || data[65] > 1 || data[66] > 1) return null;
  return {
    program: addressDecoder.decode(data.subarray(1, 33)),
    authority: optionalZeroKey(data.subarray(33, 65)),
    mutable: data[65] === 1,
    canonical: data[66] === 1,
    seed: seedString(data.subarray(67, 83)),
    encoding: data[83],
    compression: data[84],
    format: data[85],
    dataSource: data[86],
    dataLength,
    data: data.subarray(PM_HEADER_LENGTH, PM_HEADER_LENGTH + dataLength),
    accountLength: data.length,
  };
}

export type PmBufferAccount = {
  program: Address | null;
  authority: Address | null;
  canonical: boolean;
  seed: string;
  data: Uint8Array;
};

/** Buffer layout: disc 0, program 1 (zeroes = none), authority 33, canonical 65,
 *  seed 66..82 (+14 padding), data 96.. */
export function decodePmBufferAccount(data: Uint8Array): PmBufferAccount | null {
  if (data.length < PM_HEADER_LENGTH || data[0] !== AccountKind.Buffer || data[65] > 1) return null;
  return {
    program: optionalZeroKey(data.subarray(1, 33)),
    authority: optionalZeroKey(data.subarray(33, 65)),
    canonical: data[65] === 1,
    seed: seedString(data.subarray(66, 82)),
    data: data.subarray(PM_HEADER_LENGTH),
  };
}

/** PM buffer authority offset, for getProgramAccounts memcmp filters. */
export const PM_BUFFER_AUTHORITY_OFFSET = 33;

// ── Data packing ─────────────────────────────────────────────────────────────

export function compressIdl(content: Uint8Array): Uint8Array {
  return new Uint8Array(deflateSync(content));
}

/** Inflates stored IDL bytes; null when they are not valid zlib. */
export function inflateIdl(stored: Uint8Array): Uint8Array | null {
  try {
    return new Uint8Array(inflateSync(stored));
  } catch {
    return null;
  }
}
