import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Codama-generated program clients (regenerated by `npm run codegen`):
    "lib/generated/**",
    // Supabase Deno edge functions (not part of the Next.js app):
    "supabase/functions/**",
    // Playwright UI smoke output (traces, HTML report):
    "ui-smoke/.results/**",
    "ui-smoke/.report/**",
  ]),
  // The UI smoke's mock wallet, test key and fixtures stay out of the app:
  // nothing the build compiles may import ui-smoke/ (ui-smoke/bundle.spec.ts
  // checks the build output as well).
  {
    files: ["app/**", "components/**", "lib/**", "proxy.ts", "instrumentation.ts", "next.config.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        { patterns: [{ regex: "(^|/)ui-smoke(/|$)", message: "ui-smoke/ is test code: the app must not import it." }] },
      ],
    },
  },
]);

export default eslintConfig;
