import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { createNoopSigner, type Address, type Instruction } from "@solana/kit";
import { describe, expect, it } from "vitest";
import {
  IDL_HEADER,
  PM_HEADER_LENGTH,
  PM_PROGRAM,
  compressIdl,
  decodeMetadataAccount,
  decodePmBufferAccount,
  extendLengths,
  findCanonicalMetadataPda,
  inflateIdl,
  pmAllocate,
  pmClose,
  pmExtend,
  pmInitialize,
  pmSetAuthority,
  pmSetData,
  pmSetImmutable,
  pmTrim,
  pmWrite,
  writeChunks,
} from "@/scripts/chain/lib/program-metadata";

// Generated by program/scripts/fixtures/pm-vectors.mjs calling PM 0.8.0.
const FIXTURE_PATH = path.resolve(__dirname, "fixtures/program-metadata-0.8.0.json");
const fixture = JSON.parse(fs.readFileSync(FIXTURE_PATH, "utf8"));
const k = fixture.keys as Record<string, Address>;
const data = new Uint8Array(Buffer.from(fixture.dataB64, "base64"));
const signer = createNoopSigner(k.AUTHORITY);
const bufferSigner = createNoopSigner(k.BUFFER);
const view = (ix: Instruction) => ({
  program: ix.programAddress,
  accounts: (ix.accounts ?? []).map((a) => [a.address, a.role]),
  dataB64: Buffer.from(ix.data ?? new Uint8Array()).toString("base64"),
});
const canonical = { program: k.REGISTRY, programData: k.PROGRAM_DATA };

const ours: Record<string, Instruction> = {
  write: pmWrite({ buffer: k.BUFFER, authority: signer, offset: 1800, data }),
  writeFromSource: pmWrite({ buffer: k.BUFFER, authority: signer, offset: 0, sourceBuffer: k.METADATA }),
  initializeCanonicalNoData: pmInitialize({
    metadata: k.METADATA,
    authority: signer,
    ...canonical,
    system: PM_PROGRAM,
    seed: "idl",
    ...IDL_HEADER,
    data: null,
  }),
  initializeWithData: pmInitialize({ metadata: k.METADATA, authority: signer, ...canonical, seed: "idl", ...IDL_HEADER, data }),
  setAuthorityBuffer: pmSetAuthority({ account: k.BUFFER, authority: bufferSigner, newAuthority: k.AUTHORITY }),
  setAuthorityCanonical: pmSetAuthority({ account: k.METADATA, authority: signer, ...canonical, newAuthority: k.NEW_AUTHORITY }),
  setAuthorityNone: pmSetAuthority({ account: k.METADATA, authority: signer, ...canonical, newAuthority: null }),
  setDataFromBuffer: pmSetData({ metadata: k.METADATA, authority: signer, buffer: k.BUFFER, ...canonical, ...IDL_HEADER, data: null }),
  setDataInline: pmSetData({ metadata: k.METADATA, authority: signer, ...canonical, ...IDL_HEADER, data }),
  setImmutable: pmSetImmutable({ metadata: k.METADATA, authority: signer, ...canonical }),
  trim: pmTrim({ account: k.METADATA, authority: signer, ...canonical, destination: k.DESTINATION }),
  closeBuffer: pmClose({ account: k.BUFFER, authority: signer, destination: k.DESTINATION }),
  allocateCanonical: pmAllocate({ buffer: k.METADATA, authority: signer, ...canonical, seed: "idl" }),
  allocateBuffer: pmAllocate({ buffer: k.BUFFER, authority: bufferSigner }),
  extendCanonical: pmExtend({ account: k.METADATA, authority: signer, ...canonical, length: 10240 }),
};

describe("Program Metadata 0.8.0 encoders against golden vectors", () => {
  it("the fixture records its generator, PM version and package hash", () => {
    expect(fixture.generator).toBe("program/scripts/fixtures/pm-vectors.mjs");
    expect(fixture.pmVersion).toBe("0.8.0");
    expect(fixture.pmPackageJsonSha256).toMatch(/^[0-9a-f]{64}$/);
    expect(fixture.constants.programAddress).toBe(PM_PROGRAM);
    expect(fixture.constants.accountHeaderLength).toBe(PM_HEADER_LENGTH);
  });

  it.each(Object.keys(fixture.instructions))("%s matches PM byte for byte", (name) => {
    expect(ours[name], `no encoder for ${name}`).toBeDefined();
    expect(view(ours[name])).toEqual(fixture.instructions[name]);
  });

  it("covers every fixture instruction and nothing else", () => {
    expect(Object.keys(ours).sort()).toEqual(Object.keys(fixture.instructions).sort());
  });

  it("derives the canonical IDL PDAs", async () => {
    expect(await findCanonicalMetadataPda(k.REGISTRY)).toBe(fixture.canonicalIdlPdas.asset_registry);
    expect(await findCanonicalMetadataPda(k.HOOK)).toBe(fixture.canonicalIdlPdas.transfer_hook);
  });

  it("decodes Metadata and Buffer accounts with the 96-byte header", () => {
    const plain = decodeMetadataAccount(new Uint8Array(Buffer.from(fixture.accounts.metadata, "base64")))!;
    expect(plain).toMatchObject({
      program: k.REGISTRY,
      authority: null,
      mutable: true,
      canonical: true,
      seed: "idl",
      ...IDL_HEADER,
      dataLength: data.length,
      accountLength: PM_HEADER_LENGTH + data.length,
    });
    expect(Buffer.from(plain.data).equals(Buffer.from(data))).toBe(true);
    const withAuthority = decodeMetadataAccount(new Uint8Array(Buffer.from(fixture.accounts.metadataWithAuthority, "base64")))!;
    expect(withAuthority).toMatchObject({ program: k.HOOK, authority: k.NEW_AUTHORITY, mutable: false });
    const buffer = decodePmBufferAccount(new Uint8Array(Buffer.from(fixture.accounts.buffer, "base64")))!;
    expect(buffer).toMatchObject({ program: null, authority: k.AUTHORITY, canonical: false, seed: "" });
    expect(Buffer.from(buffer.data).equals(Buffer.from(data))).toBe(true);
    // Wrong discriminator and truncated data are refused.
    expect(decodeMetadataAccount(new Uint8Array(Buffer.from(fixture.accounts.buffer, "base64")))).toBeNull();
    expect(decodeMetadataAccount(new Uint8Array(40))).toBeNull();
  });

  it("round-trips zlib and compares inflated bytes", () => {
    const idl = fs.readFileSync(path.resolve(__dirname, "../idl/transfer_hook.json"));
    const packed = compressIdl(new Uint8Array(idl));
    expect(packed.length).toBeLessThan(idl.length);
    expect(Buffer.from(inflateIdl(packed)!).equals(idl)).toBe(true);
    expect(inflateIdl(new Uint8Array([1, 2, 3]))).toBeNull();
  });

  it("splits extends at 10,240 and writes at 900 bytes", () => {
    expect(extendLengths(25_000)).toEqual([10_240, 10_240, 4_520]);
    expect(extendLengths(0)).toEqual([]);
    const chunks = writeChunks(new Uint8Array(1_950));
    expect(chunks.map(([offset, chunk]) => [offset, chunk.length])).toEqual([
      [0, 900],
      [900, 900],
      [1800, 150],
    ]);
    expect(() => pmExtend({ account: k.METADATA, authority: signer, length: 10_241 })).toThrow();
  });

  const pmInstalled = fs.existsSync(path.resolve(__dirname, "../../program/node_modules/@solana-program/program-metadata"));
  it.skipIf(!pmInstalled)("live cross-check: the generator still reproduces the committed fixture", () => {
    const programDir = path.resolve(__dirname, "../../program");
    const result = spawnSync(process.execPath, ["scripts/fixtures/pm-vectors.mjs"], { cwd: programDir, encoding: "utf8" });
    expect(result.status, result.stderr).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual(fixture);
  });
});
