// Opt-in real PostgreSQL integration tests. Never connects to an existing DB.
// RUN_LOCAL_POSTGRES_TESTS=1 POSTGRES_BIN=/path/to/postgres/bin npm test -- tests/identity-privacy.postgres.test.ts
// Creates a temporary socket-only cluster, runs the actual migration, stops and
// removes that exact temporary directory. All identifiers and data are fixtures.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { LocalPostgres } from "./helpers/local-postgres";

const enabled = process.env.RUN_LOCAL_POSTGRES_TESTS === "1";
const db = new LocalPostgres();
const sql = (query: string) => db.query(query);
const asyncSql = (query: string) => db.queryAsync(query);
const ID1 = "10000000-0000-4000-8000-000000000001";
const ID2 = "10000000-0000-4000-8000-000000000002";
const WALLET1 = "11111111111111111111111111111111";
const WALLET2 = "22222222222222222222222222222222";
const TOKEN1 = "fixture-invitation-one";
const TOKEN2 = "fixture-invitation-two";
const tables = ["otc_requests", "audit_events", "asset_profiles", "issuer_profiles", "vesting_beneficiaries"];
function bind(id = ID1, token = TOKEN1, wallet = WALLET1, network = "devnet") {
  return `select public.link_client_wallet('${id}', '${token}', '${wallet}', '${network}')::text;`;
}
function nonce(id = "10000000-0000-4000-8000-000000000099") {
  return `select public.consume_siws_nonce('https://mancipatio.test', 'devnet', '${WALLET1}', '${id}', now() + interval '5 minutes');`;
}

describe.skipIf(!enabled)("0044 identity and RLS on isolated PostgreSQL", () => {
  beforeAll(() => {
    try {
      db.initialize();
      sql(`
        create role anon;
        create role authenticated;
        create role service_role bypassrls;
        create table public.clients (
          id uuid primary key, network text not null, wallet text,
          created_at timestamptz not null default now(),
          onboarding_token text unique, onboarding_token_expires_at timestamptz,
          kyc_status text not null default 'pending',
          onboarding_status text not null default 'invited',
          last_activity_at timestamptz, notes_count integer not null default 0
        );
        create table public.client_notes (
          id bigint generated by default as identity primary key,
          client_id uuid not null references public.clients(id),
          author text not null, body text not null, kind text not null
        );
        ${tables.map((table) => `create table public.${table} (id integer primary key, internal_note text); alter table public.${table} enable row level security; create policy "legacy public read" on public.${table} for select using(true); grant select on public.${table} to anon, authenticated; insert into public.${table} values (1, 'fixture private data');`).join("\n")}
      `);
      sql(readFileSync(join(process.cwd(), "supabase/migrations/0044_identity_privacy.sql"), "utf8"));
    } catch (error) {
      db.close();
      throw error;
    }
  }, 30_000);
  afterAll(() => db.close());
  beforeEach(() => {
    sql(`delete from public.client_notes; delete from public.clients; delete from public.siws_nonces;
      insert into public.clients(id, network, onboarding_token, onboarding_token_expires_at) values
      ('${ID1}', 'devnet', '${TOKEN1}', now() + interval '14 days'),
      ('${ID2}', 'devnet', '${TOKEN2}', now() + interval '14 days');`);
  });

  it("consumes a nonce exactly once across connections and a database restart", async () => {
    const results = await Promise.all(Array.from({ length: 8 }, () => asyncSql(`set role service_role; ${nonce()}`)));
    expect(results.filter((v) => v === "t")).toHaveLength(1);
    expect(results.filter((v) => v === "f")).toHaveLength(7);
    db.stop(); db.start();
    expect(sql(nonce())).toBe("f");
    expect(sql("select count(*) from public.siws_nonces;")).toBe("1");
  });

  it("denies expired nonces and keeps cleanup from making a valid nonce reusable", () => {
    expect(sql(nonce())).toBe("t");
    sql(`insert into public.siws_nonces values ('https://mancipatio.test', 'devnet', '${WALLET2}', '10000000-0000-4000-8000-000000000098', now() - interval '1 hour', now());`);
    expect(sql(nonce())).toBe("f");
    expect(sql("select count(*) from public.siws_nonces;")).toBe("1");
    expect(sql(`select public.consume_siws_nonce('https://mancipatio.test','devnet','${WALLET1}','10000000-0000-4000-8000-000000000097',now()-interval '1 second');`)).toBe("f");
  });

  it("atomically admits one wallet for an invitation and never overwrites it", async () => {
    const result = await Promise.all([asyncSql(bind()), asyncSql(bind(ID1, TOKEN1, WALLET2))]);
    const statuses = result.map((v) => JSON.parse(v).status).sort();
    expect(statuses).toEqual(["linked", "wallet_conflict"]);
    expect(sql("select count(*) from public.client_notes;")).toBe("1");
    const winner = sql(`select wallet from public.clients where id='${ID1}';`);
    sql(`update public.clients set onboarding_status='completed' where id='${ID1}';`);
    expect(JSON.parse(sql(bind(ID1, TOKEN1, winner)))).toEqual({ status: "linked", already_linked: true });
    expect(sql(`select onboarding_status from public.clients where id='${ID1}';`)).toBe("completed");
    expect(sql("select count(*) from public.client_notes;")).toBe("1");
    expect(sql(`select onboarding_token_expires_at <= now() + interval '7 days' from public.clients where id='${ID1}';`)).toBe("t");
  });

  it("admits only one of two concurrent dossiers for the same wallet", async () => {
    const results = await Promise.all([asyncSql(bind()), asyncSql(bind(ID2, TOKEN2))]);
    expect(results.map((v) => JSON.parse(v).status).sort()).toEqual(["linked", "wallet_in_use"]);
    expect(sql(`select count(*) from public.clients where wallet='${WALLET1}';`)).toBe("1");
    expect(sql("select count(*) from public.client_notes;")).toBe("1");
  });

  it("rejects wrong token, wrong network, expiry and terminal KYC without changes", () => {
    expect(JSON.parse(sql(bind(ID1, "wrong-token"))).status).toBe("invalid_invitation");
    expect(JSON.parse(sql(bind(ID1, TOKEN1, WALLET1, "mainnet"))).status).toBe("invalid_invitation");
    sql(`update public.clients set onboarding_token_expires_at=now()-interval '1 second' where id='${ID1}';`);
    expect(JSON.parse(sql(bind())).status).toBe("expired");
    sql(`update public.clients set onboarding_token_expires_at=now()+interval '1 day', kyc_status='suspended' where id='${ID1}';`);
    expect(JSON.parse(sql(bind())).status).toBe("terminal_kyc");
    expect(sql("select count(*) from public.clients where wallet is not null;")).toBe("0");
    expect(sql("select count(*) from public.client_notes;")).toBe("0");
  });

  it("denies anon/authenticated private tables and RPCs while preserving service readers", () => {
    for (const role of ["anon", "authenticated"]) {
      for (const table of tables) {
        expect(() => sql(`set role ${role}; select * from public.${table};`)).toThrow(/permission denied/);
      }
      expect(() => sql(`set role ${role}; ${nonce()}`)).toThrow(/permission denied/);
      expect(() => sql(`set role ${role}; ${bind()}`)).toThrow(/permission denied/);
      expect(() => sql(`set role ${role}; select * from public.siws_nonces;`)).toThrow(/permission denied/);
    }
    expect(sql("select count(*) from pg_policies where schemaname='public';")).toBe("0");
    for (const table of tables) {
      expect(sql(`set role service_role; select count(*) from public.${table};`)).toBe("1");
    }
  });
});
