begin read only;
set local statement_timeout='20s';
select jsonb_build_object(
 'tables',(select jsonb_agg(jsonb_build_object('key',c.relname,'kind',c.relkind,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity) order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p','v')),
 'columns',(select jsonb_agg(jsonb_build_object('key',c.relname||'.'||a.attname,'type',format_type(a.atttypid,a.atttypmod),'nullable',not a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default_hash',md5(coalesce(pg_get_expr(d.adbin,d.adrelid),'')),'anon_select',has_column_privilege('anon',c.oid,a.attnum,'SELECT'),'anon_insert',has_column_privilege('anon',c.oid,a.attnum,'INSERT'),'anon_update',has_column_privilege('anon',c.oid,a.attnum,'UPDATE'),'authenticated_select',has_column_privilege('authenticated',c.oid,a.attnum,'SELECT'),'authenticated_update',has_column_privilege('authenticated',c.oid,a.attnum,'UPDATE'),'service_select',has_column_privilege('service_role',c.oid,a.attnum,'SELECT')) order by c.relname,a.attname) from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname='public' and c.relkind in ('r','p','v') and a.attnum>0 and not a.attisdropped),
 'constraints',(select jsonb_agg(jsonb_build_object('key',c.relname||'.'||p.conname,'type',p.contype,'validated',p.convalidated,'hash',md5(regexp_replace(pg_get_constraintdef(p.oid),E'\\s+',' ','g'))) order by c.relname,p.conname) from pg_constraint p join pg_class c on c.oid=p.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'),
 'indexes',(select jsonb_agg(jsonb_build_object('key',t.relname||'.'||i.relname,'unique',p.indisunique,'valid',p.indisvalid,'hash',md5(regexp_replace(pg_get_indexdef(p.indexrelid),E'\\s+',' ','g'))) order by t.relname,i.relname) from pg_index p join pg_class t on t.oid=p.indrelid join pg_class i on i.oid=p.indexrelid join pg_namespace n on n.oid=t.relnamespace where n.nspname='public'),
 'policies',(select jsonb_agg(jsonb_build_object('key',schemaname||'.'||tablename||'.'||policyname,'command',cmd,'roles',roles,'permissive',permissive,'using_hash',md5(coalesce(qual,'')),'check_hash',md5(coalesce(with_check,''))) order by schemaname,tablename,policyname) from pg_policies where schemaname in ('public','storage')),
 'triggers',(select jsonb_agg(jsonb_build_object('key',c.relname||'.'||t.tgname,'enabled',t.tgenabled,'hash',md5(regexp_replace(pg_get_triggerdef(t.oid),E'\\s+',' ','g'))) order by c.relname,t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and not t.tgisinternal),
 'functions',(select jsonb_agg(jsonb_build_object('key',p.proname||'('||pg_get_function_identity_arguments(p.oid)||')','security_definer',p.prosecdef,'config',p.proconfig,'anon_execute',has_function_privilege('anon',p.oid,'EXECUTE'),'authenticated_execute',has_function_privilege('authenticated',p.oid,'EXECUTE'),'service_execute',has_function_privilege('service_role',p.oid,'EXECUTE'),'hash',md5(regexp_replace(pg_get_functiondef(p.oid),E'\\s+',' ','g'))) order by p.proname,pg_get_function_identity_arguments(p.oid)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prokind in ('f','p') and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e'))
) preflight;
rollback;
