begin read only;
set local statement_timeout = '20s';
select jsonb_build_object(
  'checked_at', clock_timestamp(),
  'migrations', (select jsonb_build_object('count',count(*),'head',max(version),'versions',jsonb_agg(version order by version)) from supabase_migrations.schema_migrations),
  'tables', (select jsonb_agg(jsonb_build_object('table',c.relname,'rls',c.relrowsecurity,'anon_select',has_table_privilege('anon',c.oid,'SELECT'),'authenticated_select',has_table_privilege('authenticated',c.oid,'SELECT'),'anon_insert',has_table_privilege('anon',c.oid,'INSERT'),'anon_update',has_table_privilege('anon',c.oid,'UPDATE'),'authenticated_update',has_table_privilege('authenticated',c.oid,'UPDATE'),'service_select',has_table_privilege('service_role',c.oid,'SELECT')) order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p','v')),
  'columns', (select jsonb_agg(jsonb_build_object('table',table_name,'column',column_name,'type',data_type) order by table_name,ordinal_position) from information_schema.columns where table_schema='public'),
  'policies', (select jsonb_agg(jsonb_build_object('schema',schemaname,'table',tablename,'policy',policyname,'command',cmd,'roles',roles,'permissive',permissive,'using_unrestricted',qual is null or qual='true','using_denied',qual='false','check_unrestricted',with_check is null or with_check='true') order by schemaname,tablename,policyname) from pg_policies where schemaname in ('public','storage')),
  'constraints', (select jsonb_agg(jsonb_build_object('table',c.relname,'name',p.conname,'type',p.contype,'validated',p.convalidated) order by c.relname,p.conname) from pg_constraint p join pg_class c on c.oid=p.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'),
  'indexes', (select jsonb_agg(jsonb_build_object('table',t.relname,'name',i.relname,'unique',p.indisunique,'valid',p.indisvalid) order by t.relname,i.relname) from pg_index p join pg_class t on t.oid=p.indrelid join pg_class i on i.oid=p.indexrelid join pg_namespace n on n.oid=t.relnamespace where n.nspname='public'),
  'functions', (select jsonb_agg(jsonb_build_object('name',p.proname,'security_definer',p.prosecdef,'anon_execute',has_function_privilege('anon',p.oid,'EXECUTE'),'authenticated_execute',has_function_privilege('authenticated',p.oid,'EXECUTE'),'service_execute',has_function_privilege('service_role',p.oid,'EXECUTE'),'search_path_pinned',exists(select 1 from unnest(p.proconfig) setting where setting like 'search_path=%')) order by p.proname) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'),
  'buckets', (select jsonb_agg(jsonb_build_object('bucket',id,'public',public,'file_size_limit',file_size_limit,'allowed_mime_types',allowed_mime_types) order by id) from storage.buckets where id in ('documents','client-documents','documents-confidential','document-uploads')),
  'object_counts', (select jsonb_agg(jsonb_build_object('bucket',bucket_id,'count',n) order by bucket_id) from (select bucket_id,count(*) n from storage.objects where bucket_id in ('documents','client-documents','documents-confidential','document-uploads') group by bucket_id) x),
  'other_bucket_count',(select count(*) from storage.buckets where id not in ('documents','client-documents','documents-confidential','document-uploads'))
) as preflight;
rollback;
